# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Node Girls"
workshopname: "Learn Javascript"
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is an introductory workshop for Javascript
baseurl: "/learn-js" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
# theme: node-girls

collections:
  steps:
      output: true

plugins:
  - jekyll-feed
  - jemoji

exclude:
  - Gemfile
  - Gemfile.lock
